export enum PoTableHeadings {
	poNumber = "PO #",
	payeeName = "Beneficiary Name",
	paymentMethod = "Payment Method",
	dueDate = "Due Date",
	createdDate = "Created Date",
	pnpLocation = "P&P Location",
	topicDivision = "Topic / Division",
	reportingBudgetLine = "Reporting / Budget Line",
	tax = "Tax",
	total= "Total",
	productsOrServicesDescriptionsAndPrices = "Product / SVC Description and Price",
	requestedBy = "Requested By",
	approvedBy = "Approved By",
	_id = "_id",
}
