export enum PoTableHeadings {
	poNumber = "PO #",
	payeeName = "Beneficiary Name",
	paymentMethod = "Method",
	dueDate = "Due",
	createdDate = "Created",
	location = "Location",
	topicDivision = "Topic / Division",
	reportingBudgetLine = "Reporting / Budget Line",
	subtotal = "Sub",
	tax = "Taxes",
	currency = "¤",
	total= "Total",
	productsOrServicesDescriptionsAndPrices = "Product / SVC Description and Price",
	requestedBy = "Requester",
	approvedBy = "Approver",
	_id = "_id",
}
