export const connected = `Connected to IndexedDB!`
export const deleteDatabaseError = "Error deleting database.";
export const deleteDatabaseSuccess = "Database deleted Successfully.";
export const error = `Error ❌`;
export const greeting = "Hello! 👋";
export const ifTheyHaveKey = "If you have a key, jump to step 2.";
export const ifTheyNeedNewKey = "If you need a new key, do step 1, then step 2.";
export const logoutIndexedDB = "Your IndexedDB Cryption Key database has been deleted.";
export const logoutLocalStorage = "Your cryption key file name has been deleted from local storage.";
export const noFileName = "No previous cryption file name found 🔍";
export const step1 = `Step 1: 📥 a New Cryption Key 🔐 `;
export const step2 = `Step 2: 📤 an Existing Cryption Key 🔐`;
export const success = `Success ✔`;
export const transactionComplete = `IndexedDB transaction complete.  \nYou got this 👍`;
export const warning =  `Warning ⚠`;
